### ISSUE TITLE
Unable to configure NZBHydra2: Backup folder backup does not exist and could not be created

### ISSUE THREAD

**Issue by rutskiuk** [linuxserver/docker-nzbhydra2#12]
## Expected Behavior
Expected that once the docker container was set up and running that I would be able to configure indexers

## Current Behavior
When trying to apply any kind of change to the settings I get the message from the title
![image](https://user-images.githubusercontent.com/25068977/106396988-25fdc680-6403-11eb-93e8-d01e1c009d4c.png)

## Steps to Reproduce
1. Installed the container using the following:
sudo docker run --name=NZBHydra2 -e PUID=1000 -e PGID=1000 -e UMASK=002 -e TZ=Europe/London -p 5076:5076 -v /home/pi/docker/nzbhydra2:/config -v /home/pi/downloads:/downloads --restart unless-stopped linuxserver/nzbhydra2

2. Once running I try to make any change and click save

## Environment
OS: Docker running on Raspberry Pi OS / Docker running on Synology
**CPU architecture:** x86_64 & arm32

## Docker logs

2021-01-31 19:44:57.146  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.config.ConfigWeb            : [Host: BigRig2] Received new config

Backup folder backup does not exist and could not be created

2021-01-31 19:52:22.333  WARN --- [http-nio-0.0.0.0-5] org.nzbhydra.config.BaseConfig           : [Host: BigRig2] Config validation returned errors:

2021-01-31 19:52:22.344  WARN --- [http-nio-0.0.0.0-5] org.nzbhydra.config.BaseConfig           : [Host: BigRig2] Config validation returned warnings:

2021-01-31 19:52:35.941  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.config.ConfigWeb            : [Host: BigRig2] Received new config

Backup folder /home/pi/docker/nzbhydra2/backup does not exist and could not be created

I have removed and recreated the container
I have also checked the path on the pi and can confirm /home/pi/docker/nzbhydra does exist and does have a backup, database and logs subdirectory. I have tried successfully to manually create a backup, I just cannot save any changes to the nzbhydra configuration. I have also tried manually defining an absolute path for the backup folder however that path cannot be saved. I cannot rule out user error though.

**Comment by Roxedus** [comment]
I think it just got solved upstream. https://github.com/theotherp/nzbhydra2/releases/tag/v3.11.3 Please try the new build when we have built it and report back

**Comment by Roxedus** [comment]
It is now built and pushed, do you still see this error?

**Comment by rutskiuk** [comment]
Thank you, all working now.
After a bit of tinkering I've got both Synology and Raspberry Pi docker configured and working.
