### ISSUE TITLE
Logs show OutdatedWrapperDetector

### ISSUE THREAD

**Issue by majorgiant** [linuxserver/docker-nzbhydra2#13]
Hi, Per staff request via discord a issue report. 

Hydra seems fine. But the logs in hydra show the following 

```
The NZBHydra wrappers (i.e. the executables or python scripts you use to run NZBHydra) seem to be outdated. Please update them:
Shut down NZBHydra, download the latest version and extract *all files* into your main NZBHydra folder (overwriting all). Start NZBHydra again.
```

 

Docker was installed using the official docker repo guide. 
the nzbhydra2 docker was installed using portainer. 

deleting and creating from scratch solved it. local issue

**Comment by majorgiant** [comment]
![portainer3](https://user-images.githubusercontent.com/52878827/109698500-c294bf00-7b8f-11eb-92c2-019a21182f1b.png)
![portainer2](https://user-images.githubusercontent.com/52878827/109698506-c32d5580-7b8f-11eb-9b74-66da6fe0e7a1.png)
![portainer1](https://user-images.githubusercontent.com/52878827/109698508-c32d5580-7b8f-11eb-890b-5c196d371f3d.png)

**Comment by aptalca** [comment]
the build date it's showing in the first screenshot is from Nov 2020

**Comment by majorgiant** [comment]
I destroyed the container and recreated it. it looks like the "issue" disappeared. it looks like when using portainer and pulling a new image, not everything gets updated for some reason. sorry to have wasted your time.
