### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by chripede** [linuxserver/docker-nzbhydra2#17]
After the latest update it appears the migration files has been changed

Migration checksum mismatch for migration version 1.5
-> Resolved locally    : -1164435198
-> Applied to database : -1318452055
Migration checksum mismatch for migration version 1.9
-> Resolved locally    : -89734697
-> Applied to database : 898390205
Migration checksum mismatch for migration version 1.13
-> Resolved locally    : 2009826409
-> Applied to database : 177884391
Migration checksum mismatch for migration version 1.18
-> Resolved locally    : -369596359
-> Applied to database : -1708423874
Migration checksum mismatch for migration version 1.22
-> Resolved locally    : -2084246401
-> Applied to database : -851607784
Migration checksum mismatch for migration version 1.24
-> Resolved locally    : 759637950
-> Applied to database : 2051224413
Migration checksum mismatch for migration version 4
-> Resolved locally    : -961707303
-> Applied to database : 485762902

**Comment by ghost** [comment]
I worked around this by deleting everything in /config volume except nzbhydra.yml (essentially discarding the database). The unfortunate result was the same as reported in #18 so I had to also roll back from "latest" tag to "v4.3.0-ls48"

**Comment by memmnon** [comment]
Same problem, and reverting to v4.3.0-ls48 fixes it.

**Comment by Kline-** [comment]
> I worked around this by deleting everything in /config volume except nzbhydra.yml (essentially discarding the database). The unfortunate result was the same as reported in #18 so I had to also roll back from "latest" tag to "v4.3.0-ls48"

This is what happened to me initially as well. I dumped the database and thought I was good, then stumbled on the other errors and opened #18 . I'm not sure what broke by changing the base image from Ubuntu to Alpine, but something did.
