### ISSUE TITLE
“Crashing” with latest update?

### ISSUE THREAD

**Issue by deadrubberboy** [linuxserver/docker-nzbhydra2#21]
Hello,

First, apologies for my ignorance.  Been using for years in Docker with no issues. 

Today I plulled newest image today (via Portainer recreate/pull latest as usual) and can no longer access via web and my “*arrs” are showing access error.  

I don’t really understand the logs but in Portainer it shows “main application quick unexpectedly” and seems like a lot of Java errors?

I have tried deleting both the image and container and redeploying fresh and same result.  

Known error with release? Or any advice?

thank you!

**Comment by SevereOverfl0w** [comment]
More specifically, the error I'm seeing in the logs is:

```

Logging wrapper output to /config/logs/wrapper.log
2022-08-10 17:02:58,201  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /storage/sys/fs/cgroup/cpuset.
```

---

Edit, found the closed issue regarding this.  However I'm on 20.10.17 of docker rather than an old version that is unsupported.  Setting the security_opt also hasn't resolved the issue.

**Comment by SevereOverfl0w** [comment]
I made the version parsing more robust which seems to have worked:

```
        match = None
        for line in lines:
            versionLine = line.replace("\n", "").replace("\r", "")
            match = re.match('(java|openjdk) (version )?"?(?P<major>\d+)((\.(?P<minor>\d+)\.(?P<patch>\d)+)?[\-_\w]*)?"?.*', versionLine)
            if match:
                break
```

**Comment by aptalca** [comment]
Please open a new issue. Without the issue template filled out, we have no idea what you guys are talking about.

**Comment by SevereOverfl0w** [comment]
I think it's a repeat of https://github.com/linuxserver/docker-nzbhydra2/issues/20.  Except that the resolution mentioned there hasn't worked.
