### ISSUE TITLE
[FEAT] Update to Java 17

### ISSUE THREAD

**Issue by theotherp** [linuxserver/docker-nzbhydra2#25]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'm planning to require JDK 17 at some point but it's already supported. Could you please release a prerelease / beta image using JDK 17 to prepare for that?

### Reason for change

Ensure future compatibility.

**Comment by Roxedus** [comment]
We can fairly easily move the dev tag to 17, does that suffice?

**Comment by theotherp** [comment]
That should be fine, thanks.
