### ISSUE TITLE
[FEAT] WebUI slowed by DNS

### ISSUE THREAD

**Issue by guyman624** [linuxserver/docker-nzbhydra2#27]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

For whatever reason, under some circumstances the WebUI is extremely slow, because it is trying to resolve the hostname of the accessing device. The previous fix I found on reddit was manually setting another DNS in the container.

I have found that another solution is to disable "Map Hosts" from the webui settings. Since "Log IP addresses" is disabled by default in this container, the "Map Hosts" setting is actually hidden but it appears that it is still running anyway. The issue is that when it logs the IP addresses, it tries to resolve the hostname of the logged device, however, it is still attempting to resolve the hostname even while logging is disabled. Disabling the setting resolves the issue.

### Reason for change

It makes the software much more tolerable and fluid

**Comment by thespad** [comment]
We'll check and see if it's possible to configure on our end when we do the initial container setup.

**Comment by pagdot** [comment]
Seems like it can be disabled in [baseConfig.yml#L297](https://github.com/theotherp/nzbhydra2/blob/844dafce2e5a5ae94cf0f0f4e4bcce69512aa882/core/src/main/resources/config/baseConfig.yml#L297)

The default seems to be for ip logging to be enabled though
