### ISSUE TITLE
Manual backup / Automatic backup not working 

### ISSUE THREAD

**Issue by Desolator-FRL** [linuxserver/docker-nzbhydra2#3]
This issue is also posted at: https://github.com/theotherp/nzbhydra2/issues/542
It is closed there because it is an issue with the Docker container.
There is also an thread on Reddit about this problem: https://old.reddit.com/r/nzbhydra/comments/fwm4r2/cant_create_backup/

The backup function doesn't work anymore.

When I try to make a manual backup there is an error and this is the log output : "Unexpected error when client tried to access path /internalapi/backup/backup. Error message: Could not find acceptable representation"

and:

"java.io.IOException: Unable to create backup target folder /app/nzbhydra2/backup"
(rest in attached zip file).

I tried to change the backup target folder in Hydra (program and yml) and tried to change the path in the Docker container.

[nzbhydra-debuginfos-2020-04-22-09-55.zip](https://github.com/linuxserver/docker-nzbhydra2/files/4518557/nzbhydra-debuginfos-2020-04-22-09-55.zip)

**Comment by tobbenb** [comment]
Which path did you set for the backup in nzbhydra?
You could probably also do a volume mount to /app/nzbhydra2/backup.

**Comment by theotherp** [comment]
It was my fault. Should be fixed with 2.19.6. Sorry about that.

**Comment by tobbenb** [comment]
Thanks for letting us know.

**Comment by nemchik** [comment]
This should be released now. Closing. If there's further issue let us know.
