### ISSUE TITLE
dev tag refers to outdated version

### ISSUE THREAD

**Issue by theotherp** [linuxserver/docker-nzbhydra2#4]
Currently running `linuxserver/nzbhydra2:dev` gets you v2.19.0 which in https://github.com/theotherp/nzbhydra2/blob/master/core/src/main/resources/changelog.json is the last version whith `"final": false`. But there's already a newer version which is final.

The `dev` tag should always just refer to the latest version in that document (or just the latest release here: https://github.com/theotherp/nzbhydra2/releases).

Thanks!

**Comment by nemchik** [comment]
I'll look into this.

**Comment by nemchik** [comment]
Closing. Should be fixed now.

**Comment by theotherp** [comment]
Thanks.
